### ISSUE TITLE
double check GB survey lengths

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/ms-keyrun#58]
Plots of lengths by species and year look much less smooth than might be expected from survey data. The plot below is all years aggregated, still a bit spiky, and is that huge haddock spike at ~10 cm real?

![image](https://user-images.githubusercontent.com/8172302/219701854-6c8e06c1-b679-4c78-91f0-135de2d6ac40.png)

**Comment by sgaichas** [comment]
@andybeet I believe the plot was generated using [this code from gavin's hydradata fork](https://github.com/thefaylab/hydradata/blob/master/data-raw/lenbintests.R) but it has been a while

**Comment by sgaichas** [comment]
@andybeet I think the code in that file runs as a standalone now, needed one more line. See updated file [here](https://github.com/thefaylab/hydradata/blob/master/data-raw/lenbintests.R).

**Comment by andybeet** [comment]
So, @sgaichas, i think you are right. There is something wrong with the data. I believe it is how i processed it. I tried to be clever and i think it was far from that! I want to chat to @slucey about this.

So the length data in mskeyrun is not the raw survey lengths but expanded to represent numbers based on swept area estimates. Saying this i did the calculations incorrectly.
