### ISSUE TITLE
simFisheryLencompSubannual not unique rows

### ISSUE THREAD

**Issue by vbartolino** [NOAA-EDAB/ms-keyrun#84]
Subannual length distributions have unexpectedly multiple rows for the same species,year,step,length

```
simFisheryLencompSubannual %>% filter(Code=="NCO" & year == 50 & fishMonth==3) %>% head(20)
```

**Comment by sgaichas** [comment]
Thanks @vbartolino, I think I know what is going on, is it only for Cod/NCO?
This species has 4 fleets which I'm thinking are improperly aggregated. I will check, thanks for the heads up.

**Comment by vbartolino** [comment]
@sgaichas it seems to be for most species (I checked HAD, BWH, MAC, RED)

**Comment by sgaichas** [comment]
@vbartolino just pushed a correction: I think this works now? Please let me know if you still see problems, and thanks again.
